#!/bin/bash

# Emit default cache headers for static assets so edge/CDN layers can cache
# them instead of re-fetching from origin (and origin storage, e.g. EFS) on
# every request. mod_expires only applies when the response has no Expires
# header already, so apps that manage their own caching are unaffected.
# Disable with QUANT_STATIC_CACHE=0; tune TTL with QUANT_STATIC_CACHE_TTL
# (seconds, default 7 days).

QUANT_STATIC_CACHE="${QUANT_STATIC_CACHE:-1}"
QUANT_STATIC_CACHE_TTL="${QUANT_STATIC_CACHE_TTL:-604800}"
CONF=/etc/apache2/conf-enabled/quant-static-cache.conf

if [ "$QUANT_STATIC_CACHE" != "1" ]; then
    rm -f "$CONF"
    exit 0
fi

cat > "$CONF" <<EOF
# Generated by 04-static-cache-headers.sh (QUANT_STATIC_CACHE_TTL=${QUANT_STATIC_CACHE_TTL}s)
<IfModule mod_expires.c>
    ExpiresActive On
    ExpiresByType image/jpeg "access plus ${QUANT_STATIC_CACHE_TTL} seconds"
    ExpiresByType image/png "access plus ${QUANT_STATIC_CACHE_TTL} seconds"
    ExpiresByType image/gif "access plus ${QUANT_STATIC_CACHE_TTL} seconds"
    ExpiresByType image/webp "access plus ${QUANT_STATIC_CACHE_TTL} seconds"
    ExpiresByType image/avif "access plus ${QUANT_STATIC_CACHE_TTL} seconds"
    ExpiresByType image/svg+xml "access plus ${QUANT_STATIC_CACHE_TTL} seconds"
    ExpiresByType image/x-icon "access plus ${QUANT_STATIC_CACHE_TTL} seconds"
    ExpiresByType text/css "access plus ${QUANT_STATIC_CACHE_TTL} seconds"
    ExpiresByType text/javascript "access plus ${QUANT_STATIC_CACHE_TTL} seconds"
    ExpiresByType application/javascript "access plus ${QUANT_STATIC_CACHE_TTL} seconds"
    ExpiresByType font/woff "access plus ${QUANT_STATIC_CACHE_TTL} seconds"
    ExpiresByType font/woff2 "access plus ${QUANT_STATIC_CACHE_TTL} seconds"
    ExpiresByType font/ttf "access plus ${QUANT_STATIC_CACHE_TTL} seconds"
    ExpiresByType application/vnd.ms-fontobject "access plus ${QUANT_STATIC_CACHE_TTL} seconds"
</IfModule>
EOF

echo "✅ Static asset cache headers enabled (TTL ${QUANT_STATIC_CACHE_TTL}s)"
