# This workflow is an example of how you can build and push this codebase to Quant Cloud.
# Use this as a starting point for your own workflow if you are forking this repository.
name: Build and Push Apache+PHP to Quant Cloud

on:
  push:
    branches:
      - develop
      - main
      - feature/*
    tags:
      - '*'

concurrency:
  group: build-and-push-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Initialize Quant Cloud
        uses: quantcdn/quant-cloud-init-action@v1.1.5
        id: init
        with:
          quant_organization: ${{ secrets.QUANT_ORGANIZATION }}
          quant_api_key: ${{ secrets.QUANT_API_KEY }}

      - name: Build and push Apache+PHP image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: |
            ${{ steps.init.outputs.stripped_endpoint }}/${{ secrets.QUANT_ORGANIZATION }}/${{ steps.init.outputs.quant_application }}:apache-php-${{ steps.init.outputs.image_suffix_clean }}
          cache-from: type=gha,scope=php8.4
          cache-to: type=gha,mode=max,scope=php8.4

      - name: Create environment from production if it doesn't exist
        if: ${{ !startsWith(github.ref, 'refs/tags/') && steps.init.outputs.environment_exists == 'false' }}
        uses: quantcdn/quant-cloud-environment-action@v1.3.0
        with:
          api_key: ${{ secrets.QUANT_API_KEY }}
          organization: ${{ secrets.QUANT_ORGANIZATION }}
          app_name: ${{ steps.init.outputs.quant_application }}
          environment_name: ${{ steps.init.outputs.environment_name }}
          from_environment: production
          image_suffix: ${{ steps.init.outputs.image_suffix_clean }}

      - name: Wait for environment creation to complete
        if: ${{ !startsWith(github.ref, 'refs/tags/') && steps.init.outputs.environment_exists == 'false' }}
        run: sleep 120

      - name: Translate docker-compose.yml
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: quantcdn/quant-cloud-compose-action@v1.1.2
        id: compose
        with:
          api_key: ${{ secrets.QUANT_API_KEY }}
          organization: ${{ secrets.QUANT_ORGANIZATION }}
          compose_file: docker-compose.yml
          image_suffix: ${{ steps.init.outputs.image_suffix_clean }}

      - name: Apply docker-compose updates to environment
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: quantcdn/quant-cloud-environment-action@v1.3.0
        with:
          api_key: ${{ secrets.QUANT_API_KEY }}
          organization: ${{ secrets.QUANT_ORGANIZATION }}
          app_name: ${{ steps.init.outputs.quant_application }}
          environment_name: ${{ steps.init.outputs.environment_name }}
          operation: update
          compose_spec: ${{ steps.compose.outputs.translated_compose }}
